### ISSUE TITLE
Mu-argus, tau-argus

### ISSUE THREAD

**Issue by John-Czajka** [sdcTools/UserSupport#149]
*Please specify*  
**SDC tool used:** (mu-argus, sdcMicro, sdcMicroGUI, tau-argus, sdcTable)  
**Version used:**  
**Operating system used:** (Windows, Linux)
Since some time in July, all references to Mu-Argus and Tau-Argus have been removed from the cbs.nl website, and none of the previous links works. I sent a query to cbs.nl, and I got a response that I would get a quicker answer by submitting an issue to this email address. What's up?
---

**Comment by ppdewolf** [comment]
I suppose you refer to the site http://neon.vb.cbs.nl/casc?
This is an alias of the site http://research.cbs.nl/casc. Somehow the webserver of this site seems down.
Due to the corona situation we need to work from home. As a consequence I cannot access the webserver. So even if it was "up" I couldn't update to the latest versions of mu- and tau-argus. I have reported the fact that the server is "down" to our IT support staff. Hopefully they will be able to fix this soon.

So, at the moment, the best way to get the latest versions of mu- and tau-argus is to go to [https://sdctools.github.io/UserSupport/](https://sdctools.github.io/UserSupport/) and navigate to the `Releases` subpage.

**Comment by John-Czajka** [comment]
Thank you, Peter-Paul. Oddly, even a search of the Statistics Netherlands website for Argus turns up nothing. Very odd. Anyway, I will go to the github site you suggest.

John

**Comment by ppdewolf** [comment]
For your information: on the Statistics Netherlands website, it is possible to get some information on the use of mu- and tau-argus in our office (see e.g. https://www.cbs.nl/en-gb/our-services/methods/statistical-methods/output/output/statistical-disclosure-control) 
However, since the development of mu- and tau-argus has been coming from several joined Euopean projects (partly funded by Eurostat), we do not give direct access to the software on our official Statistics Netherlands website. 

We hope that the [casc website](research.cbs.nl/casc) will be up and running again soon and at the same time hope that https://sdctools.github.io/UserSupport/ will become a new landing page for more SDC software than only mu- and tau-argus.

**Comment by John-Czajka** [comment]
Thank you, again!
