### ISSUE TITLE
unable to open tau_testW on TauArgus

### ISSUE THREAD

**Issue by yilingsg** [sdcTools/UserSupport#150]
**SDC tool used:**  tau-argus
**Version used:**  TauArgus4.2.0b5
**Operating system used:** Win10 

Hello, I'm a new user and  I've just downloaded https://github.com/sdcTools/tauargus/releases/download/4.2.0b5/TauArgus4.2.0b5Windows32bit.zip. After launching TauArgus, I tried to open tau_testW to no avail - please see screenshot. Would you be able to advise if there are certain settings that i need to configure? Thank you. 

[Doc1.docx](https://github.com/sdcTools/UserSupport/files/5072512/Doc1.docx)

---

**Comment by ppdewolf** [comment]
It may seem a bit confusing, but you actually _did_ open tau_testW :smile. 

Since tau-argus is software to protect _tables_, when you only loaded microdata it will not know which table you want to analyse/protect. So you do not see a table at that point: you first have to specify that table.

When you open/load a microdata file, you will see that some more menu items have become available. E.g. `Specify/Metadata...` and, if you also specified a metadtafile `Specify/Tables...`. 

Please have a look at the "tour of tau-argus" chapter of the manual (chapter 3) or the [step by step example](https://github.com/sdcTools/manuals/blob/master/tau-argus/Step-by-step%20test%20procedure%20%20TauArgus.pdf). The step by step example is based on a slightly older version but basically is still valid.

**Comment by yilingsg** [comment]
gosh, that's right! thank you so much for your prompt response. will get started on the step by step example.
