### ISSUE TITLE
Decimal places in .tab files :bug: 

### ISSUE THREAD

**Issue by bjanez** [sdcTools/UserSupport#177]
**SDC tool used:** Tau Argus  
**Version used:**  4.1.4, 4.2.b, 4.4.2
**Operating system used:** Windows 10

---
Hello!

I would like to ask you for some ideas/possible solutions of why the Modular method for secondary suppression of the data in the .tab format file I present below,  crashes (closes)  in Tau Argus versions 4.1.4 (Build 1) and 4.2.0 (Build 5) . We just tested the new version of 4.2.2 and we now get an error message, but the program doesn’t crash (close) anymore. 
When we tried different things, like changing the .rda and also modifying the tabular data, we noticed that Modular method successfully finished, if we lowered the number of decimals places for upper and lower protection interval in the .tab file.  We would be very grateful to have more clarification on this issue especially since we have one very similar .tab file where we don’t have to lower the number of decimal places for the Modular method to successfully complete the secondary suppression.   

Kind regards,

Janez Bijec (Statistics  Slovenia)
[issue.zip](https://github.com/sdcTools/UserSupport/files/7761329/issue.zip)

**Comment by ppdewolf** [comment]
Hi Janez,

there are a few observations from my side on the table you provide in the `issue.zip` file:

1. The frequencies of your table do not add up.
2. There are cells with the value zero: is the value indeed exactly zero (i.e. all contributors contribute 0 or the positive and negative contributions exactly (up to the last decimal) cancel out)?
3. The cells with value zero and status `U` have a protection interval [-10, 0].
4. The protection limits (upl and lpl) have many decimals and we end up with protection intervals with boundaries having up to 17 significant digits (e.g. for cell `"H53";"S34_SK"` we get the protection interval [ 180646730780.60363, 180732197819.39637] ).

Ad 1: This is not necessarily a "problem" with tau-argus, but is in the first place not logical and secondly I cannot ensure that it will never lead to undesirable effects.
Ad 2: If these cells are instead "empty" cells, you should treat them as "empty" (i.e. no contributors and no cell value, denoted by `-` in tau-argus' table view).
Ad 3: The negative lower bound is strange. Especially if all contributors (and all other cells) are non-negative.
Ad 4: In the first place it is rather unnecssary to enforce protection levels with 5 decimals (i.e. accuray up to 1E-5) when the cell value itself is of the order 1E+11. This level of accuracy does not really make sense in this situation. Secondly, you thus end up with 17 significant digits. Machine precision cannot deal with that many significant digits correctly (at least not in the implementation we use). It can deal with at most 13 significant digits.

So in this particular situation I would suggest to drop all decimals from the protection levels: they do not make sense and cause numeric problems in combination with the large cell values.

The fact that previous versions crashed and version 4.2.2 produces an error message is exactly what is mentioned in the description on the download page of this pre-relase: `More unfeasible tables will be detected without crashing. An error message wil be given instead.`
This particular table seems infeasible because of the large number of significant digits (e.g., may lead to apparent non-additivity).
