### ISSUE TITLE
Missing values in .tab files 

### ISSUE THREAD

**Issue by bjanez** [sdcTools/UserSupport#178]
**SDC tool used:** Tau Argus 
**Version used:**  4.2.b, 4.4.2
**Operating system used:** Windows 10
---
We would like some clarification how to handle the missing values in the .tab files. The version which we use at the moment in our production is 4.1.4, we use general SAS code for creation of tabular data format. In the latest versions of Tau Argus (4.2.b and 4.2.2) some .tab files are not working (we have the issue with missing values, written with the sign “.”)  . The following part of .tab file: “H51";"S34_S3";0;.;"S";1;1
 causes problems and we get errors when we try to specify table in 4.2.b and 4.2.2 versions, but we don’t get an error message when we specify table in 4.1.4 version of Tau Argus. 
When we change this part of the file to:
“H51";"S34_S3";0;0;"S";1;1
We don’t get any error messages and Tau Argus successfully creates the table.  We would kindly ask you not to change the formats of the input files (.rda, .tab, .arb) as they are a part our production system and they are created with general SAS code. If you need to change some of these files, we would propose to write it clearly in the documentation.

Kind Regards, 

Janez Bijec (Statistics Slovenia)

**Comment by ppdewolf** [comment]
In 4.1.4 (and earlier versions) a non-numeric value for numeric variables (like the frequency) was ignored. That is, it was detected as an exception ("catched")  but no action was taken upon that. Luckily, in your situation that still led to "expected" behaviour. In other situations it could lead to undesirable side-effects. So from 4.1.5 onwards we added an action when such an exception was caught: we now display an error message stating that the value in the .tab file is non-numeric when expecting a numeric value. This was mentioned in the release notes of version 4.1.5 onwards as "Added many checks when reading tabular input".

So we did not change the format of the .tab file, we added checks on the input to ensure more stability when reading tabular input. We did not realize that some users may use our (in 4.1.4) incorrect handling of the exceptions as a "feature" ;-) 

In your particular example, you specify a cell value of zero with unknown number of contributions. This is exactly one of the situations that should not occur: an explicit cell-value (i.e. there are contributors)  with unknown number of contributions.

Empty cells (cells with no contributors) have always been denoted with a particular status (e.g. "E"). We also allow the number of contributions to be equal to 0, what would result in an empty cell when the cell value equals 0 as well. When the cell value is unequal to zero AND the frequency is zero, you will get an error message that a cell with a non-zero value cannot have zero contributors.

Moreover, in 4.1.4 when using `“H51";"S34_S3";0;.;"S";1;1`, due to the incorrect handling of the exception, you would end up with a cell with value zero and one contributor. From 4.1.5 onwards, when using `“H51";"S34_S3";0;0;"S";1;1` you will end up with an empty cell (denoted by `-` in tau-argus' table view).

For all numeric values, an empty field (so e.g. `“H51";"S34_S3";;;"S";1;1`) or a dash (so e.g. `“H51";"S34_S3";-;-;"S";1;1`) would be equal to "missing". But even when using "missing" like this, there will still be checks on the (logical) validity of the input. E.g. `“H51";"S34_S3";;1;"S";1;1` would give the error message `An empty cell can not have a real frequency`.

When changing format of any of the input files we will obviously mention it in the release notes. Unfortunately, like in your situation, it may happen that we do not always recognize a fix as a "format-change" when the erroneous pre-fix situation was used as a "feature".

I will close this issue. If you have further questions you can reopen the issue.
