### ISSUE TITLE
TAU-Argus - Linked Tables - Error running the cover table

### ISSUE THREAD

**Issue by KarinaKelleher** [sdcTools/UserSupport#261]
**SDC Tool Used: TAU-Argus with Xpress solver
Version used: Version 4.2.4 Build 2
Windows**
---
We are currently trialing the Xpress commercial solver for use with TAU-Argus. As part of this we are testing the linked tables function (modular). However we are getting "Error running the cover table - Returned value 1" when we run this. I noted that previous issues with this were resolved by having no spaces in the filepath or by updating versions (I was using TAU-Argus version 4.2.0 Build 5 but updated to 4.2.4 Build 5 hoping that this issue would be resolved). 

I'm attaching some test files to demo this and also the relevant screenshot and log file.

Any help on this would be very much appreciated,
Karina.

[logbook_linkedtablescheck.txt](https://github.com/sdcTools/UserSupport/files/13215690/logbook_linkedtablescheck.txt)
[TestData.zip](https://github.com/sdcTools/UserSupport/files/13215722/TestData.zip)

**Comment by ppdewolf** [comment]
Hi,

Thanks for the test files. This really helped in locating the problem.

The problem occurs because your variable codes start with a dot (`.`), e.g., `. IE04`. In writing the hierarchy files for the linked modular approach, a dot is used to denote the levels. This interferes with the starting dot of your code. 
I will have to look into the code at several places where the dot is hard-coded in writing the hierarchy files for the modular approach, to change this.

Note by the way that even trying to protect a single table with modular using your hierarchy-files with codes starting with a dot would crash tau-argus (for the same reason).

I'll put this on the list as a bug, but it will take some time to solve it correctly (it is intertwined with several procedures).

Workaround: replace your dot at the start of a code by another character, e.g. `*`

**Comment by KarinaKelleher** [comment]
Hi,

That's great - Thank you for the very prompt reply and solution - Should be an easy fix for us which is always good to hear! We'll replace the dots - We have been using optimal on tables so was never really an issue until now,

Thanks again
