### ISSUE TITLE
Protection of linked tables in tau-Argus

### ISSUE THREAD

**Issue by Benjamin-Fuchs** [sdcTools/UserSupport#265]
SDC Tool: Tau-Argus
Version: 4.2.3 Build 1
Operation system used: Windows 10
---

Dear all,

with the support of @ppdewolf  (Peter-Paul) and @sven-grunwald (Sven) I was able to write a batch file to implement a minimum frequency and p% rule for protecting an already existing table. Once again, many thanks for your very helpful comments!

To be honest, I am struggling again with two major (at least for me) problems.

**Problem 1: No successful protection of linked tables with modular using tau-argus interface** 

I’ve tried to protect two tables that are linked. Instead of a batch file I used the interface in a first step. Tau-argus reads both tables and implement successfully a minimum frequency and p% rule for both tables. However, when trying to implement a secondary suppression for linked tables via “Modify → Linked tables” I get the following error message when using modular. 

![errormessage](https://github.com/sdcTools/UserSupport/assets/126875531/2cd63622-39dd-492f-9f93-ae91953396c1)

Hybercube seems to work. However, I am not sure whether tau-argus implements the secondary suppression protection for both tables combined. 

The first table includes information of number of vehicles for federal states (NUTS 1) and type of vehicle; the second table includes number of vehicles for districts (NUTS 3) and type of vehicle. Both tables should be linked via type of vehicle. Just for clarification: I know that I could combine both tables and define federal state/district as one variable with a hierarchical structure. For this case, I just try to learn how to use tau-argus for two linked tables.

I’ve been trying to solve this problem for several days; I can’t find my mistake. Can someone tell me what I do wrong? I added the files I have used for my tests: Input1.tab includes the first table; Input2.tab the second table. Input1_meta.rda and Input2_meta.rda are the corresponding metadata files. (I renamed the file extension to "log", otherwise i am not able to attach them) TablesExplained.xls tries to explain the content of Input files in more detail. 

**Problem 2: Implementing protection of two linked tables via batch file**

I am not sure how to write a batch file correctly for the combined protection of two linked tables. I do not exactly know in which order I have to define both tables and to implement to suppression commands. In the manual (version 4.1) I haven’t seen any examples for implementing a combined protection of two linked tables. Can anybody give me a hint?

I greatly appreciate any help.

Best 
Benjamin

[Input1.log](https://github.com/sdcTools/UserSupport/files/13458852/Input1.log)
[Input1_meta.log](https://github.com/sdcTools/UserSupport/files/13458853/Input1_meta.log)
[Input2.log](https://github.com/sdcTools/UserSupport/files/13458854/Input2.log)
[Input2_meta.log](https://github.com/sdcTools/UserSupport/files/13458855/Input2_meta.log)
[TablesExplained.xls](https://github.com/sdcTools/UserSupport/files/13458856/TablesExplained.xls)

**Comment by sven-grunwald** [comment]
Hi Benjamin,

corresponding to your second question, please find attached an example for a batch file of a linked Argus run. You first specify your first table just like you do it in a single run. Afterwards the same for the second table, followed by the <Readtable> statement. Then you choose the method of your secondary suppression, in the example it is modular. If I remember correctly, the first paramater indicates whether it is a linked run or not, so the "0" should call the linked algorithm. At the end the results are stored in a csv-file.

[example.txt](https://github.com/sdcTools/UserSupport/files/13459148/example.txt)

Concerning your first question, I think you should have variables Argus can build a cover table from. So in your case, you just have two different ways to seperate your districts (NUTS1 / NUTS3). Argus won't know wheter the one is a subdivision of the other one or not, so it cannot build a covertable. If you choose NUTS1 for your first table and a hierarchical structure (NUTS1/NUTS3 so that Argus knows that NUTS3 is in lower hierarchie of NUTS1 and which codes of the NUTS3 level sum up to which NUTS1 code) for your second, it should work.

**Comment by julienjamme** [comment]
Dear Benjamin,

If you are not reluctant to work on R, you can take a look at the package `rtauargus`. The function called `tab_multi_manager()` manages the links between the tables and runs Tau-Argus to protect one table at a time. It could be interesting if you have a lot of linked tables (tens or more) to deal with. The documentation of the function is [here](https://inseefrlab.github.io/rtauargus/articles/protect_multi_tables.html) and the source of the package  [here](https://github.com/inseefrlab/rtauargus).

Best,
Julien

**Comment by ppdewolf** [comment]
Hi Benjamin,

as @sven-grunwald indicated, for your second question, you should use table number 0 in the `<SUPPRESS>` (e.g., the `<SUPPRESS>  MOD(0,1,1,0,0)` as Sven suggested in the `example.txt`). The first argument of the suppress routine is always the table number it should be applied to. Using table number 0 means that all specified tables should be treated as linked tables.

Concerning your first question: again @sven-grunwald is correct. Tau-argus needs to be told that the two tables are using the "same" spanning variable (NUTS) and their relationship. The linked approach with modular expects the following: 

- all tables should have the same safety rules (p%-rule etc.)
- all tables should have the same respons variable (nvehicles) 
- there should be at least one "common" spanning variable (NUTS)

Tau argus is capable of recognising the common variable if it has the same name, and a cover hierarchy is possible. According to the manual: 
```
When protecting a set of linked tables the restriction is that all tables are a sub-set
of a theoretical cover table. The cover table is formed by building a table spanned
by all explanatory variable from the individual tables and using the longest code
list for each dimension. The dimensions are decided by looking for different names
of explanatory variables.

In the current implementation there is one restriction. For each of the spanning
variables in the cover table the codelist and the hierarchy should be present in one
of the linked tables. For all other tables the codelists and the hierarchy should be a
subset of this cover hierarchy. And of course the set of linked tables should be
consistent. The cells that are logical the same should have exactly the same value
and status. If not the protection of the cover table will fail.
```
As @sven-grunwald mentioned, it would work if you choose NUTS1 for your first table and a hierarchical structure (NUTS1/NUTS3) for your second. See attached example files: [example.zip](https://github.com/sdcTools/UserSupport/files/13471413/example.zip)
But note that in this instance the use of the linked approach is "overkill": the second table in the example.zip now has all levels and sublevels and in fact is the cover table itself.

**Comment by Benjamin-Fuchs** [comment]
Dear all,
thank you very much for your efforts and help! Sorry for my late replay, I hope your new year has started well.

@julienjamme: Thank you very much for the hint! Unfortunately, I am not experienced in R.
@sven-grunwald: Thank you very much! Your example helped me a lot. In my case, I was able to produce an executable batch file when trying to protect two identical tables (which doesn’t make any sense in real life but the batch file works without any error messages.) Whenever I try to protect two tables that are slightly different, I get different error messages with respect to the data structure or dependencies.
@ppdewolf: Thank you very much! I tried to execute your example **via menu** at first. 
However, I always get an error message due to non-additivity with zero observations for federal states. 

![errormessage3](https://github.com/sdcTools/UserSupport/assets/126875531/857b0839-055a-479f-ae03-975f041d973d)

In your example you defined the hierarchy structure in the second metadata file that characterizes the districts table.
In a second trial, I put the information on the hierarchy structure in the Input1.rda metafile and deleted it in the Input2.rda metafile. Input1 metafile characterizes the federal states table. I get a similar error message with zero observations for districts, however. Then, I put the information on the hierarchy structure in both metafiles and got the same error message as in the second case.

**Question 1**: It seems that Tau Argus does not get the connection between districts and federal states successfully (?). Can you tell me, in which rda file I have to name the hierarchy structure?

Further, I tried variations of the federal state table as a second table to check how linked table protection works. 

**Question 2**: First I used the information on number of vehicles (by vehicle type) of one federal state as a second table. However, I got the following error message

![errormessage](https://github.com/sdcTools/UserSupport/assets/126875531/f7312287-5d69-4de1-a537-a08c6c9c06b9)
					Bundesland = federal state

**Question 3**: Then I split the federal states table into two further parts (just like I would split a full sample into a male and female sample) and tried to protect those three tables (full sample and 2 subsamples) simultaneously. Primary suppression works. Secondary suppression simultaneously for all three tables didn’t work. I got the following error message.

![errormessage2](https://github.com/sdcTools/UserSupport/assets/126875531/c9bdf89a-9641-42e2-9787-828b4163807c)

The reported inconsistencies are related to the fact that the number of observations in both subsamples (male/female) separately (!) are not identical with the number of observations in the full sample. This irritates me, because subsamples are always smaller than the full sample. After the error message Tau-Argus gives an overview for those cases. With respect to the manual you have cited; is it possible with Tau-Argus to protect such kind of table dependency?

In sum: It seems that I am not able to tell Tau-Argus successfully how two (or more) tables are linked. 

**A possible bug(?)**: When checking frequency tables I always get an error message when naming the frequency variable explicitly. Using “<freq>” works. 
"Var1" "Var2" | "Frequency Variable" | "" | "" => Doesn’t work
"Var" "Var2" | "<freq>" | "" | "" => works

Best
Benjamin

**Comment by sven-grunwald** [comment]
Hi Benjamin,

concerning question 1: I think your example.zip doesn't really makes sense. You would have to specify the connection between total, federal state and districts in one single tab-file, you cannot manage that with the help of the linked tables option. So you need at least one data file where you have them all together. In your case the second data file would then automatically be completly included in the first one and because of that irrelevant.

A typical use case for us would be if the first dimension has more hierarchical level in table 1 and the second dimension has more levels in table 2. You could modify your example in that way that you have total, federal states and districts in the first table (so without type of vehicles!) and in the second table you have total and federal states (so not districts!) combined with type of vehicles in the second table. Then you have to specify the hierarchie for NUTS in the first rda for sure.

If a spanning variable is hierarchical (so it has more than total an one sublevel), you always have to mention the correct hrc-file in the rda. If both tables are hierarchical concerning NUTS, you have to include a hrc-file for both tables. But you cannot expect that Argus creates the "missing" links between federal states and districts, if you do not have them in at least one of your tables. You cannot describe them just in your hrc-file. The hrc-file always belongs to a certain tab-file.

I think, if you understand what i tried to describe, the other two questions could also be clear. 

Best,
Sven

**Comment by ppdewolf** [comment]
@sven-grunwald Actually it was me that provided part of the example.zip and forgot to adjust the second tab-file 😁 
But I fully agree with your explanation.
There might be a slight difficulty with the category names. Spaces in front or at the back of categories sometimes cause problems. Attached a version of the example files that works for me.

[example_v2.zip](https://github.com/sdcTools/UserSupport/files/13949110/example_v2.zip)
