### ISSUE TITLE
set secondary suppressions in inner cells (instead of marginal cells )

### ISSUE THREAD

**Issue by sven-grunwald** [sdcTools/UserSupport#34]
*Please specify*  
**SDC tool used:** Tau-Argus
**Version used:**  3.5.0_build_27 and 4.1.0_build_2
**Operating system used:** Windows

Instance_2 shows the case, where a secondary suppression is set into a marginal cell instead of the remaining inner cell. We use a lamda value of 0.4 and that is why inner cell and marginal cell obtain the same costs. But also in case of same costs inner cells should be preferred as secondary suppression compared to marginal cells. So there should be added some kind of exta protection for marginal cells.

In case of the littlte instance results are the same for TauArgus V_3.5.0_build_27 and v_4.1.0_build_2 with settings Modular, "Do singletons" and lambda=0.4, but in general we experience this behaviour much more often with version 4.1.

[Instance_2.zip](https://github.com/sdcTools/UserSupport/files/621996/Instance_2.zip)

---

**Comment by ppdewolf** [comment]
In Modular with hierarchical tables, each subtable will get ensured that marginal weights are larger than interior-cell weights (needed for the backtracking mechanism). For non-hierarchical tables and for Optimal, we did not implement this: then the user is more in control of supplying the table-data (including the costs). Some users do not want the marginals to have higher weights "by default".
There is also some "scaling" of the costs and mapping them to integers (as needed in the CSP-routines). Mapping to integers may results in same costs for cells that differ only in the n-th decimal of the costs. This may also occur for lambda=1.

This issue is related to Issue #7

**Comment by ppdewolf** [comment]
Problem was related to issue #7. As stated, in modular marginals will always get larger weight/cost.
