### ISSUE TITLE
Tau-Argus : Modular does not work well with hrc where some lvl are equals

### ISSUE THREAD

**Issue by julienlemasson** [sdcTools/UserSupport#66]
**SDC tool used:** Tau-Argus
**Version used:**  3.5 (same issue with 4.1.5)
**Operating system used:** Windows seven Pro 64b---

Hi, 
I have a case pretty weird where Modular does not protect correctly the tabulation.
I tried to simplify here as mch as possible :
[issue with Modular.zip](https://github.com/sdcTools/UserSupport/files/1106032/issue.with.Modular.zip)

I've got a hrc file with some sub level that are equal to the agregation :
12
@120
@@1200
@@@1200Z
For reasons (because of linked tables), only the 1200Z case is in primary secret. When I applie modular on the table, the agregations are not suppressed.
And what is weirder it's that on my original table, I had some others branches in the same configuration that were correctly protected (I've not managed to keep that on my example).
 
Thanks
Julien Lemasson.

**Comment by AncoHundepool** [comment]
Dear Julien,

For me this table is inconsistent.
The same cell in different levels of the hierarchy having the same value but sometimes it is safe and sometimes not.
TAU expects a complete table.
How should he solve the problem that the same cell is sometimes safe and sometimes not?
Should the highest level prevail or the lowest?

Please note
1. Modular removes these trivial level and protects the reduced table. That is an enormous gain in processing time during all the back-tracking procedures.
2. When changing a cell in the apriori procedure, TAU will be so polite and apply the changes to all the equal cells in a trivial hierarchy.

**Comment by ppdewolf** [comment]
Like Anco said, tau-argus expects (as tabular input) a table with consistent status of cells. Cell 1200 and cell 1200z are "the same cell", so the yshould have the same status. Since in this case it is not calculated by tau-argus, but given by the user, tau-argus does not know which status is the correct one: should they both be safe or both be primary unsafe?

As an enhancement/feature we could think about issuing a warning when tau-argus detects such inconsistencies in status.

Workarounds for the moment:

1. Make sure the tabular input is consistent w.r.t. the status of cells
2. Use apriori procedure with "expand for trivial levels" selected (e.g. use the apriori file [pp.hst.txt](https://github.com/sdcTools/UserSupport/files/1111103/pp.hst.txt))

For now I close this issue. I'll add a new issue on the possible enhancement.
3. Use microdata (or tabular data with enough additional info) and have tau-argus determine the primary unsafe cells

**Comment by julienlemasson** [comment]
Thank you all for your answers.

The complexity of the tabulation leads me to import secret from an another tabulation, that ventilate only a some the activity codes. So the 1200, 120 and 12 are not in the apriori because missing from the original tabulation. 
Anyway I get why that does not work well. I guess a warning at this time could be useful, indeed.

I just try the "expand for trivial levels" and it works well. I see this has been added in the batch mode, so I think it get an entire solution to my issue !

For the last point, in fact, the 1200Z is not secret because of primary secret, but because of secondary secret from another tabulation.

Thanks again, 
Best regards.
