### ISSUE TITLE
tau-Argus

### ISSUE THREAD

**Issue by LuigiVirgili** [sdcTools/UserSupport#73]
*Please specify*  
**SDC tool used:**  (tau-argus)  
  **Operating system used:** (Windows 7, 10)

1) Saving table with <<Intermediate format>>: a tabel saved selecting <<itermediate format>> cannot be readback (with the option "use given status") because the error reported in attach. This happend using version 4.1.6 build 2. The same table, saved as intermediate format, can be readback using the tau-Argus 3.5.0 build27 version. 

[tau-argus _error.docx](https://github.com/sdcTools/UserSupport/files/1341152/tau-argus._error.docx)

2) The Rounding method, in the latest version 4.1.6 build 2, seems to run with cplex only; it does not work setting the free solver (in a previous version, e.g. 4.1.3 build 1, the Rounding method works with the free solver). 

3) Specify tables: tau-argus allow you to set parameters Ind-1 and Ind-2 for the 3 rules Dominance, P% and Request, what the Ind-2 parameters are referred to? 

Best regards
---

**Comment by ppdewolf** [comment]
1. Apparently you used the "intermediate" format to save the table. This format is intended to be used to save a table such that it can be read back into tau-argus. However, you used it on a protected table (the "M" status that is in the error is given to a secondary suppression). It is not possible to read a table with secondary suppressions into tau-argus. That's why you get the error.
2. It is still possible to use the free solver with the Rounding method. Apparently it checks for the cplex license file in all situations (with any solver). **Workaround**: just put an empty file named access.ilm in the tau-argus directory. We will remove this check in the future when not using Cplex.
3. Some countries use two dominance rules at the same time (e.g., (1,75) together with (2,80)). So in that case you would specify the (1,75) rule with the Ind-1 parameters and the (2,80) rule with teh Ind-2 parameters. The same with multiple p% and request rules.

**Comment by LuigiVirgili** [comment]
Thank you for your help.
About the "intermediate format":
Yes, I used the intermediate option to save the protected table, and I tried to read it back. This is because in version 3.5.0 built 27 the "intermediate format" option produced the  .tab, .rda, .hrc files, and the protected table could be read back into tau-Argus (even if it contained the "M" code: secondary suppression status).

**Comment by ppdewolf** [comment]
Just curious: for what purpose do you read a protected table back into tau-argus?

**Comment by LuigiVirgili** [comment]
In the attached file, all the steps 
[tau_intermediate.docx](https://github.com/sdcTools/UserSupport/files/1349484/tau_intermediate.docx)

**Comment by ppdewolf** [comment]
Oeps. You're right, it is not possible in 4.1.6b2. We'll look into it.

**Comment by AncoHundepool** [comment]
The status M will now be accepted when reading a table saved as intermediate.

**Comment by AncoHundepool** [comment]
And with respect to the solver issue: Just check whether the CPlex licence file you specified in the options window really exists. Even if you do not use CPlex, the file name should be either empty or specify an existing file.
If you use the free solver then the content of the Cplex licence file is irrelevant as long as it exists.

**Comment by LuigiVirgili** [comment]
I am using the free solver. 
I saved an empty file named access.ilm in the tau-argus directory and now i can run the rounding method. 
About the "intermediate problem" i keep getting the same error message related to the "M" status .
Setting and error message are saved  in the attached file
[setting_&_error.docx](https://github.com/sdcTools/UserSupport/files/1352655/setting_._error.docx)

**Comment by AncoHundepool** [comment]
Sorry Luigi.
I have amended the code and reported that here.
But you have to wait till a new release, before you can use this option.

**Comment by ppdewolf** [comment]
In the next release (version 4.1.7) the check for Cplex licence file while using other solvers in Rounder will also be fixed (then workaround no longer needed).
