### ISSUE TITLE
Rounding procedure and Xpress

### ISSUE THREAD

**Issue by aicabrera** [sdcTools/UserSupport#85]
**SDC tool used:** tau-argus
**Version used:**  4.1.6b2
**Operating system used:** Windows

---
I am trying to use the rounding procedure in tau-argus to protect a small frequency table. I am using an Xpress licence. However, I keep getting an error message "Error in the rounding procedure. Cplex licence file ... could not be found". Does the rouding procedure require a cplex licence to work? Is it possible to get it work with Xpress?

**Comment by ppdewolf** [comment]
This will be fixed in the new release. We checked for the Cplex licence even when using a different solver. Possible workaround: just put an empty file `foo.ilm` somewhere and select that as licence file for Cplex in the `Options` dialog. Press `OK`. Go back to `Options` and select XPress as solver. Most likely, the rounding will now use Xpress as solver.
