### ISSUE TITLE
Regarding "Error with modular method and three linked tables #92"

### ISSUE THREAD

**Issue by jj585** [sdcTools/UserSupport#93]
I am trying to protect tables for Labour cost survey 2016 and I need to protect several magnitude tables where dimension variables are "size by enterprise" and "economic activity". Response variables are "number of employees", "hours actually worked", "paid hours", "labour costs" and "information on units" (5 tables in total).

The problem is with dimension "economic activity" as I can't define hierarchy properly in top-down approach for this dimension. Groups or subtotals/totals needed are not mutually exclusive or disjoint (see section 3.4.2 on page 22 in document "LCS2016 implementing arrangments - FINAL.pdf". It can be seen also when trying to construct a binary tree that it is not possible to include all subtotals needed in one binary tree. For example in the 1st tree (see nace_tree1.pdf), there is no groups XGSO, XG_S and XO_S included which I include in the 2nd and 3rd trees.

Therefore I introduced 3 equal columns in micro-data that represent economic activity with different names (nace1, nace2 and nace3 respectively) and defined three separate hierarchies to cover all subtotals needed and tried to protect them as linked tables.

Is my approach actually correct in the first place?
Is there any better solution to this problem when it is not possible to define a hierarchy for a dimensional variable in one file other than to protect via linked table approach?

[LCS2016 implementing arrangments - FINAL.pdf](https://github.com/sdcTools/UserSupport/files/2117957/LCS2016.implementing.arrangments.-.FINAL.pdf)
[nace_tree1.pdf](https://github.com/sdcTools/UserSupport/files/2117959/nace_tree1.pdf)
[nace_tree2.pdf](https://github.com/sdcTools/UserSupport/files/2117960/nace_tree2.pdf)
[nace_tree3.pdf](https://github.com/sdcTools/UserSupport/files/2117961/nace_tree3.pdf)

**Comment by julienlemasson** [comment]
Hi, 
I work for Insee (France), on the confidentiality questions.
 
We allready had to deal with that kind of hierarchies, that is to say "not mutually exclusive or disjoint" as you said.
 
For few years, we used to do the manual way :
- we treated the part of the tabulation that fits well with Tau-Argus (with hrc files)
- we treated the "specials agregate" in some sas's procedures, with simple rules like : if the special agregate is concerned by primary secret, or if only one of its components is in secret then the agregate is secret.
 
For now, we try as often as possible to applicate this rule that is pretty like your approach :
- we create several hierarchies from the original variable
- we protect the table with all these hierarchies in the same table (not with linked table).
From your example we'd do : nace1*nace2*nace3*size
Of course the issue of this approach is to increase the number of variables and to exceed the limit for modular ... or even for hypercube.
Since the variable is secretised 3 times, it is theoretically possible (not sure if that it is actually possible) to get for a specific code two differents status : lets's say that for nace1="X23" we get unsafe and nace2="X23" and nace3= "X23" we get safe results.
To deal with that possibility, we can add a sas procedure that check that every code gets that same status on the three variable nace1, 2 and 3.
If it is not the case, we would produce an apriori file forcing the concerned codes in "unsafe" status for the three variables.
Then ... we re-do the Tau-Argus procedure ... and re-checked the coherence of the status.
... And again until every codes get the same status on the three nace variable.
 
This approach can be heavy to do, so the batch mode could be really helpfull there.

**Comment by mancag** [comment]
Dear jj585,

As far as I know, in your example, it is not possible to protect tables using linked tables approach in Tau-Argus, because variable nace can't be defined properly in top-down approach. Defining variables with different names nace1, nace2, nace3 is not a solution, because the variable has to have the same name in all tables for linked protection.
I suggest you solve your problem in the following way: protect each table separately and transfer protection with the help of history file or manually: 
-	In microdata, have only variable nace.
-	Define 3 different hierarchies for variable nace (nace1.hrc, nace2.hrc, nace3.hrc) and recode them according to the attached file nace_hierarchies.xlsx (the hierarchies are the same as in your attached files nace_tree1.pdf, nace_tree2.pdf, nace_tree3.pdf, only the recode for nace2 and nace3 is less detailed).
-	Protect the table with nace1. Keep this table opened in Tau-Argus.
-	Make history file from Code-value + Add Status output of secondary protected table with nace1 (option Generate apriory).
-	Define table with nace2. Import information from table with nace1, using A priori info button to import the history file. Suppress table with nace2. Remember, only GSO and G_S are new in this table, all other nace codes have already been protected in table with nace1, so they have to have the same suppression pattern.
-	Define table with nace3. Import information from table with nace1, using A priori info button to import the history file. Suppress table with nace3. Remember, only O_S is new in this table, all other nace codes have already been protected in table with nace1, so they have to have the same suppression pattern.
-	If protection of table with nace2 or table with nace3 is not successfull, you can change the suppression pattern in table with nace1 and repeat the procedure. If transfering protection with the history file is not successful, you can transfer protection manually.

Best regards,
Manca Golmajer
Statistical Office of the Republic of Slovenia

[nace_hierarchies.xlsx](https://github.com/sdcTools/UserSupport/files/2128470/nace_hierarchies.xlsx)

**Comment by sven-grunwald** [comment]
Hi jj585,

I totally agree with Mancas solution. In addition to clarify the last bullet point:

If I create the suppression patterns for tables with nace2.hrc and nace3.hrc, it might be the case that I get a suppression for one or more of the new subtotals, e.g. for GSO in table with nace2. That would cause another suppression in B_F, which might not be necessary after protection of table with nace1. So I have to carry over this new suppression to table 1 again, which means I have to circle between the three tables as long as I get new suppressions. 

Best,
Sven
Federal Statistical Office of Germany

**Comment by ppdewolf** [comment]
No additional comments lately, so I'll close this issue. It is of course archived 😃
